runtime: java17
instance_class: F2
env_variables:
  SPRING_APPLICATION_NAME: vmproject
  SPRING_DATASOURCE_URL: jdbc:mysql://34.142.199.65:3306/vaccinedb?useUnicode=yes
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: +78|gIfk?5IUMk.O
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_SHOW_SQL: true
  SPRING_DATA_JDBC_DIALECT: mysql
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
  SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE: 10MB
